package(default_visibility = ["//visibility:public"])

py_test(
    name = "fs_test",
    srcs = ["fs.py"],
    deps = [
        "//store/fs:fs",
         "@bazel_tools//third_party/py/mock",
    ],
)
